#pragma once

#define MENU_DATA_FORCE_BK_REDRAW 0xFEEE
#define MENU_REDRAW_BORDER TRUE

// ACRYLIC

#define ACRYLIC_OPACITY_LIGHT 200
#define ACRYLIC_OPACITY_DARK  190

#define ACRYLIC_TINT_AUTO TRUE

#define ACRYLIC_TINT_LIGHT    0xEEEEEE
#define ACRYLIC_TINT_DARK     0x2B2B2B

// POPUP_HOVER

#define POPUP_HOVER_OPACITY_LIGHT 17
#define POPUP_HOVER_OPACITY_DARK  65

#define POPUP_HOVER_COLOR_LIGHT RGB(0, 0, 0)
#define POPUP_HOVER_COLOR_DARK  RGB(128, 128, 128)

#define POPUP_HOVER_COLOR_OPAQUE_LIGHT RGB(POPUP_HOVER_OPACITY_LIGHT, POPUP_HOVER_OPACITY_LIGHT, POPUP_HOVER_OPACITY_LIGHT)
#define POPUP_HOVER_COLOR_OPAQUE_DARK  RGB(POPUP_HOVER_OPACITY_DARK, POPUP_HOVER_OPACITY_DARK, POPUP_HOVER_OPACITY_DARK)

// POPUP_SEPARATOR

#define POPUP_SEPARATOR_COLOR_LIGHT RGB(38, 38, 38)
#define POPUP_SEPARATOR_COLOR_DARK  RGB(217, 217, 217)

#define POPUP_SEPARATOR_OPACITY_LIGHT 48
#define POPUP_SEPARATOR_OPACITY_DARK  48

///////////////////////////////////////////////////////

#define WIN10_MENU_REDRAW_BORDER_DARK FALSE

#define WIN11_SET_SMALL_CORNERS FALSE
#define WIN11_SET_POPUP_BORDERS FALSE

#define WIN11_POPUP_BORDER_LIGHT RGB(217, 217, 217)
#define WIN11_POPUP_BORDER_DARK  RGB(48, 48, 48)

#define WIN11_OUTLINE_LIGHT RGB(0, 0, 0)
#define WIN11_OUTLINE_DARK  RGB(255, 255, 255)

#define WIN11_LUMINOSITY_TINT_LIGHT  0x9EF9F9F9
#define WIN11_LUMINOSITY_TINT_DARK   0x412B2B2B

#define WIN11_LUMINOSITY_TINT_OPACITY_LIGHT  158
#define WIN11_LUMINOSITY_TINT_OPACITY_DARK   65

///////////////////////////////////////////////////////